#!/usr/bin/env python3
"""Check committed fixtures against outputs regenerated by the real Java engine."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("generated", type=Path)
args = parser.parse_args()
expected = ROOT / "apple/AudiverisCore/Tests/AudiverisCoreTests/Fixtures"
actual_files = {p.name: p for p in args.generated.glob("*.json")}
expected_files = {p.name: p for p in expected.glob("*.json")}
if not actual_files or actual_files.keys() != expected_files.keys():
    raise SystemExit(f"Oracle file sets differ: generated={sorted(actual_files)}, committed={sorted(expected_files)}")
for name in sorted(actual_files):
    if json.loads(actual_files[name].read_text(encoding="utf-8")) != json.loads(expected_files[name].read_text(encoding="utf-8")):
        raise SystemExit(f"Java oracle mismatch: {name}; review before regenerating reference outputs")
manifest = json.loads(actual_files["manifest.json"].read_text())
if manifest["caseCount"] != len(actual_files) - 1:
    raise SystemExit("Oracle case count does not match its manifest")
print(f"PASS: {manifest['caseCount']} native reference cases match the real Java engine")
